
define(
[
	'./ECMA_RESERVED_WORDS',
	'./HTML_SPECIAL_CHARS',
	'./REGEX_SPECIAL_CHARS'
]
, function (
	ECMA_RESERVED_WORDS,
	HTML_SPECIAL_CHARS,
	REGEX_SPECIAL_CHARS
) 
{'use strict';

return {
	ECMA_RESERVED_WORDS : ECMA_RESERVED_WORDS,
	HTML_SPECIAL_CHARS  : HTML_SPECIAL_CHARS,
	REGEX_SPECIAL_CHARS : REGEX_SPECIAL_CHARS
};

});

/**
* @namespace Sumi.Const
*/
